version: '3.8'

services:
  mock-api:
    build: .
    container_name: mock-price-api
      
    volumes:
      - railway_data:/app/data
      - railway_images:/app/images
      
    environment:
      - FLASK_ENV=production
      - PORT=5000 
    restart: unless-stopped

volumes:
  railway_data:
  railway_images: